"""
journey_builder.py

Calls the Claude API with the journey research prompt to generate a
complete 28-day digital health journey, then builds an Excel spreadsheet
matching the NeuroFlow template column structure exactly.

Columns (matching Journey_Design_Template):
  Step Name | Day | Required? | Topic | Type | Copy |
  Character Count (=LEN formula) | Flesch-Kincaid Ease Score (>79) |
  Link | Citations | Review Date | Reviewers | Comments

Outputs:
  /tmp/<topic>_journey.xlsx
  /tmp/journey_videos.json  (video topics with full sequence metadata)

Usage:
  python agents/journey_builder.py "Depression Management"
"""

import os
import sys
import json
import re
import anthropic
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter


PROMPT_PATH = os.path.join(os.path.dirname(__file__), "..", "prompts", "journey_research.txt")

NF_NAVY = "161B4A"
WHITE   = "FFFFFF"
ALT_ROW = "F4F5FB"


# ── Reading level ─────────────────────────────────────────────────────────────

def count_syllables(word):
    word = re.sub(r"[^a-z]", "", word.lower())
    if len(word) <= 3:
        return 1
    if word.endswith("e"):
        word = word[:-1]
    return max(1, len(re.findall(r"[aeiouy]+", word)))


def flesch_ease(text):
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"\b[a-zA-Z]+\b", text)
    if not sentences or not words:
        return 0.0
    syllables = sum(count_syllables(w) for w in words)
    score = 206.835 - 1.015 * (len(words) / len(sentences)) - 84.6 * (syllables / len(words))
    return round(max(0.0, min(100.0, score)), 1)


# ── Sequence metadata ─────────────────────────────────────────────────────────

def extract_key_points(video_activity):
    """
    Return the key_points summary for a video activity.

    Prefers the explicit key_points field generated by the journey prompt,
    which names the specific concepts, evidence points, and conclusions the
    video establishes. Falls back to a truncated version of the copy text
    if key_points is absent (e.g. for journeys generated before this update).
    """
    # Prefer the dedicated key_points field
    key_points = (video_activity.get("key_points") or "").strip()
    if key_points:
        return key_points

    # Fallback: truncate copy text at the last complete sentence within 200 chars
    copy_text = (video_activity.get("copy") or "").strip()
    if len(copy_text) <= 200:
        return copy_text
    truncated = copy_text[:200]
    last = max(truncated.rfind("."), truncated.rfind("!"), truncated.rfind("?"))
    if last > 100:
        return truncated[:last + 1]
    return truncated.rstrip() + "..."


def build_sequence_metadata(video_topics, journey_name):
    """
    Second pass over the collected video list. Adds:
      sequence_position  — 1-indexed position within the video sequence
      total_videos       — total number of videos in the program
      journey_name       — program name used for narrative framing
      adjacent_context   — previous and next video topic + key_points

    Doing this as a second pass means every video already exists in the
    list before we start looking up its neighbors.
    """
    total = len(video_topics)
    enriched = []

    for idx, video in enumerate(video_topics):
        prev_ctx = None
        if idx > 0:
            prev = video_topics[idx - 1]
            prev_ctx = {
                "topic":      prev["topic"],
                "key_points": extract_key_points(prev)
            }

        next_ctx = None
        if idx < total - 1:
            nxt = video_topics[idx + 1]
            next_ctx = {
                "topic":      nxt["topic"],
                "key_points": extract_key_points(nxt)
            }

        enriched.append({
            **video,
            "sequence_position": idx + 1,
            "total_videos":      total,
            "journey_name":      journey_name,
            "adjacent_context":  {
                "previous": prev_ctx,
                "next":     next_ctx
            }
        })

    return enriched


# ── Claude API ────────────────────────────────────────────────────────────────

def generate_journey(topic, context=""):
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    with open(PROMPT_PATH) as f:
        base_prompt = f.read()

    context_block = f"\nADDITIONAL CONTEXT: {context}" if context.strip() else ""
    label = f"{topic} ({context})" if context.strip() else topic
    print(f"Generating journey for: {label}")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=8096,
        messages=[{"role": "user", "content": f"{base_prompt}\n\nJOURNEY TOPIC: {topic}{context_block}"}]
    )

    raw = response.content[0].text.strip()
    raw = re.sub(r"^```(?:json)?\s*\n?", "", raw, flags=re.MULTILINE)
    raw = re.sub(r"\n?```\s*$", "", raw, flags=re.MULTILINE)

    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            return json.loads(match.group())
        raise ValueError(f"Could not parse Claude response as JSON: {e}")


# ── Excel builder ─────────────────────────────────────────────────────────────

def header_cell(ws, row, col, value):
    c = ws.cell(row=row, column=col, value=value)
    c.fill = PatternFill("solid", fgColor=NF_NAVY)
    c.font = Font(color=WHITE, bold=True, size=10)
    c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)


def data_cell(ws, row, col, value, alt=False):
    c = ws.cell(row=row, column=col, value=value)
    if alt:
        c.fill = PatternFill("solid", fgColor=ALT_ROW)
    c.alignment = Alignment(wrap_text=True, vertical="top")
    c.font = Font(size=10)


def build_xlsx(journey_data, topic, output_path):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Template"

    headers = [
        "Step Name", "Day", "Required?", "Topic", "Type", "Copy",
        "Character Count (automatic)", "Flesch-Kincaid Ease Score (>79)",
        "Link", "Citations", "Review Date", "Reviewers", "Comments"
    ]

    for col, h in enumerate(headers, 1):
        header_cell(ws, 1, col, h)
    ws.row_dimensions[1].height = 30

    # Journey description row
    jd    = journey_data["journey_description"][:500]
    jname = journey_data["journey_name"][:35]
    ws.cell(row=2, column=1, value="--").font = Font(size=10)
    data_cell(ws, 2, 4, jname)
    data_cell(ws, 2, 5, "Journey Description")
    data_cell(ws, 2, 6, jd)
    ws.cell(row=2, column=7, value="=LEN(F2)").font = Font(size=10)
    data_cell(ws, 2, 8, flesch_ease(jd))
    ws.row_dimensions[2].height = 80

    # Activity rows — first pass
    raw_videos = []

    for idx, activity in enumerate(journey_data["activities"]):
        row = idx + 3
        alt = (row % 2 == 0)

        step_name = (activity.get("step_name") or "")[:35]
        day_val   = activity.get("day", "")
        required  = activity.get("required", "")
        act_topic = (activity.get("topic") or "")[:35]
        act_type  = activity.get("type", "")
        copy_text = (activity.get("copy") or "")[:400]
        link      = activity.get("link", "")
        citations = activity.get("citations", "")
        fke       = activity.get("fk_ease") or flesch_ease(copy_text)

        data_cell(ws, row, 1,  step_name,      alt)
        data_cell(ws, row, 2,  day_val,         alt)
        data_cell(ws, row, 3,  required,        alt)
        data_cell(ws, row, 4,  act_topic,       alt)
        data_cell(ws, row, 5,  act_type,        alt)
        data_cell(ws, row, 6,  copy_text,       alt)
        ws.cell(row=row, column=7, value=f"=LEN(F{row})").font = Font(size=10)
        if alt:
            ws.cell(row=row, column=7).fill = PatternFill("solid", fgColor=ALT_ROW)
        data_cell(ws, row, 8,  round(fke, 1),  alt)
        data_cell(ws, row, 9,  link,            alt)
        data_cell(ws, row, 10, citations,       alt)
        for c in [11, 12, 13]:
            data_cell(ws, row, c, "", alt)

        ws.row_dimensions[row].height = 70

        if act_type.lower() == "video":
            raw_videos.append({
                "step_name":  step_name,
                "topic":      act_topic,
                "copy":       copy_text,
                "key_points": (activity.get("key_points") or "").strip(),
                "day":        day_val
            })

    # Second pass: enrich with sequence metadata
    video_topics = build_sequence_metadata(raw_videos, journey_data["journey_name"])

    # Column widths
    for col, w in enumerate([28,7,10,30,25,65,16,22,35,55,14,14,20], 1):
        ws.column_dimensions[get_column_letter(col)].width = w

    ws.freeze_panes = "A3"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}1"

    # Info tab
    ws2 = wb.create_sheet("Info")
    info = [
        "Generated by NeuroFlow Content Automation",
        f"Journey topic: {topic}",
        f"Total activities: {len(journey_data['activities'])}",
        f"Video activities: {len(video_topics)}",
        "Review Date, Reviewers, and Comments columns are left blank for end-user completion."
    ]
    for i, text in enumerate(info, 1):
        ws2.cell(row=i, column=1, value=text).font = Font(size=11)

    wb.save(output_path)
    print(f"Spreadsheet saved: {output_path}")
    return video_topics


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python agents/journey_builder.py <topic>")
        sys.exit(1)

    topic   = sys.argv[1]
    context = sys.argv[2] if len(sys.argv) > 2 else ""
    safe    = re.sub(r"[^\w\s-]", "", topic).replace(" ", "_")
    out     = f"/tmp/{safe}_journey.xlsx"

    journey_data = generate_journey(topic, context)
    video_topics = build_xlsx(journey_data, topic, out)

    print(f"\nVideo sequence ({len(video_topics)} videos):")
    for v in video_topics:
        pos   = v["sequence_position"]
        total = v["total_videos"]
        prev  = v["adjacent_context"]["previous"]
        nxt   = v["adjacent_context"]["next"]
        print(f"  [{pos}/{total}] Day {v['day']}: {v['topic']}")
        if prev:
            print(f"    <- Previous: {prev['topic']}")
        if nxt:
            print(f"    -> Next:     {nxt['topic']}")

    with open("/tmp/journey_videos.json", "w") as f:
        json.dump({
            "journey_name":     journey_data["journey_name"],
            "journey_topic":    topic,
            "spreadsheet_path": out,
            "video_topics":     video_topics,
            "total_activities": len(journey_data["activities"])
        }, f, indent=2)

    print("\njourney_builder complete.")
